### PR TITLE
:bug::traffic_light: Update karma preprocessors (fixes noref)

### PR DESCRIPTION
**Pull request by SpainTrain**
This change is [Reviewable](https://reviewable.io/reviews/homezen/redux-variants/3)

### CODE REVIEW

**Comment by SpainTrain** [comment]
n=1 this appears to have fixed it

**Comment by SpainTrain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 3 \[r1\]](https://reviewable.io:443/reviews/homezen/redux-variants/3#-KNnojVh0VCNThCNZh-f:-KNnojVh0VCNThCNZh-g:-1189238483) ([raw file](https://github.com/homezen/redux-variants/blob/c335dc8822720a15dccd4715375b9b5d2ab4c48a/package.json#L3)):*
> ```JSON
> {
>   "name": "redux-variants",
>   "version": "1.0.0",
> ```

```
$ npm info redux-variants version
1.0.0
```

if this doesn't match what is in npm, the next release will fail

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/3)*

**Comment by SpainTrain** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[package.json, line 88 \[r2\]](https://reviewable.io:443/reviews/homezen/redux-variants/3#-KNnstt8oYMG9NjgZeDU:-KNnstt9y9MadAY5VE_w:117002417) ([raw file](https://github.com/homezen/redux-variants/blob/890c36973d1e386f731597e0745234d05939e1a0/package.json#L88)):*
> ```JSON
>     "debug": "^2.2.0",
>     "es6-error": "^3.0.0",
>     "lodash": "^4.13",
> ```

FYI because webapp cannot use 4.14 yet

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/3)*

**Comment by pcgilday** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/3)*

**Comment by pcgilday** [comment]
:shipit: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/3#-:-KNnvljEnkujip1dNuLV:1148172450)*

**Pull request merged**
