### PR TITLE
:gift_heart: Extract variants tools into lib (fixes noref)

### PR DESCRIPTION
**Pull request by SpainTrain**
- reducer for Redux
- HoC for React
- variant extractor for web servers
- middleware for express

connect home-buddy/homebuddy-webapp#1589

---
This change is [Reviewable](https://reviewable.io/reviews/homezen/redux-variants/1)

### CODE REVIEW

**Comment by pcgilday** [comment]
Reviewed 24 of 26 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[.eslintrc.yaml, line 2 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn-NZdAS9SFX_ZAcrf:-KNn-NZdAS9SFX_ZAcrg:1355738332) ([raw file](https://github.com/homezen/redux-variants/blob/c4ff37c6b143829fa3f29741f7f0c4f05aa45c87/.eslintrc.yaml#L2)):*
> ```YAML
> ---
>     root: true
> ```

Is there a good way to centralize this so that all js repos we have could share a lint file (I'm sure there is, but I haven't thought about it much)? If there is a good way to do this I think it is worth creating a ticket for it for later.

---

*[.npmignore, line 21 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn-q6q9Rf6ubqOEjd0:-KNn-q6q9Rf6ubqOEjd1:-1966769380) ([raw file](https://github.com/homezen/redux-variants/blob/c4ff37c6b143829fa3f29741f7f0c4f05aa45c87/.npmignore#L21)):*
> ```
> lib/**/*.test.js.map
> lib/test-helpers.js
> lib/test-helpers.js.map
> ```

`/lib` doesn't exist in this repo. I am fine leaving so that our ignore files are generic and common between repos if that is the goal. 

---

*[src/express-variants.test.js, line 44 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn1GfQ2BSysB8snNJ1:-KNn1GfRTdIPv54d5zho:1714539561) ([raw file](https://github.com/homezen/redux-variants/blob/c4ff37c6b143829fa3f29741f7f0c4f05aa45c87/src/express-variants.test.js#L44)):*
> ```JavaScript
>     })
> 
>     it('leaves `req.variants` alon if it already exists', () => {
> ```

typo `alon` -> `alone`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Comment by pcgilday** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn7KqvwFDJd762iF3F:-KNn7Kqw7-1pO_QxVS4f:408815690) (no related file):*
Couple minor comments then :shipit: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Comment by SpainTrain** [comment]
Reviewed 12 of 26 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[.eslintrc.yaml, line 21 \[r1\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNmc0NJxYyCU2ySPmB2:-KNmc0NJxYyCU2ySPmB3:-1698060493) ([raw file](https://github.com/homezen/redux-variants/blob/0d05830d4838bbc5e2e10d80f4a44c6b57e38041/.eslintrc.yaml#L21)):*
> ```YAML
>         - plugin:react/recommended
>         - plugin:lodash/recommended
>     rules:
> ```

BTW

so need to move this into its own plugin

---

*[.eslintrc.yaml, line 2 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn-NZdAS9SFX_ZAcrf:-KNnBRtuevsFUMfsVAaE:-1566501760) ([raw file](https://github.com/homezen/redux-variants/blob/707e455336ab9ffc977aba3d3ba0ab3fc29b4d1f/.eslintrc.yaml#L2)):*
<details><summary><i>Previously, pcgilday (Patrick Gilday) wrote…</i></summary>
> Is there a good way to centralize this so that all js repos we have could share a lint file (I'm sure there is, but I haven't thought about it much)? If there is a good way to do this I think it is worth creating a ticket for it for later.
</details>
that's what my comment 20 lines below is about

just the rules need to be centralized (actually modularized into our es5, es6, lodash, react).  The rest is intrinsically by repo.   It is easy to copy or use something like https://github.com/eslint/generator-eslint

---

*[.npmignore, line 21 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn-q6q9Rf6ubqOEjd0:-KNnBp0UihqV_yPDvVVT:-506686636) ([raw file](https://github.com/homezen/redux-variants/blob/707e455336ab9ffc977aba3d3ba0ab3fc29b4d1f/.npmignore#L21)):*
<details><summary><i>Previously, pcgilday (Patrick Gilday) wrote…</i></summary>
> `/lib` doesn't exist in this repo. I am fine leaving so that our ignore files are generic and common between repos if that is the goal. 
</details>
um, yes it does. It is where the built javascript files go.  Have you run the test, build, or most any other npm script for this repo?

---

*[src/express-variants.test.js, line 44 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn1GfQ2BSysB8snNJ1:-KNnCBLJmbabUU4t2CrO:-499146009) ([raw file](https://github.com/homezen/redux-variants/blob/707e455336ab9ffc977aba3d3ba0ab3fc29b4d1f/src/express-variants.test.js#L44)):*
<details><summary><i>Previously, pcgilday (Patrick Gilday) wrote…</i></summary>
> typo `alon` -> `alone`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Comment by SpainTrain** [comment]
*[.eslintrc.yaml, line 2 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn-NZdAS9SFX_ZAcrf:-KNnCvxqOf5CyDB6trTu:-2062973083) ([raw file](https://github.com/homezen/redux-variants/blob/707e455336ab9ffc977aba3d3ba0ab3fc29b4d1f/.eslintrc.yaml#L2)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary>
> that's what my comment 20 lines below is about
> 
> just the rules need to be centralized (actually modularized into our es5, es6, lodash, react).  The rest is intrinsically by repo.   It is easy to copy or use something like https://github.com/eslint/generator-eslint
</details>
meant https://www.npmjs.com/package/generator-eslint-init

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Comment by pcgilday** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[.eslintrc.yaml, line 2 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn-NZdAS9SFX_ZAcrf:-KNnDJnwUXM6aFQ_1vIn:1078251999) ([raw file](https://github.com/homezen/redux-variants/blob/707e455336ab9ffc977aba3d3ba0ab3fc29b4d1f/.eslintrc.yaml#L2)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary>
> meant https://www.npmjs.com/package/generator-eslint-init
</details>
weird, I didn't see that comment in my review. 

---

*[.npmignore, line 21 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn-q6q9Rf6ubqOEjd0:-KNnCYbSXCou32dRB0B-:1071181439) ([raw file](https://github.com/homezen/redux-variants/blob/707e455336ab9ffc977aba3d3ba0ab3fc29b4d1f/.npmignore#L21)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary>
> um, yes it does. It is where the built javascript files go.  Have you run the test, build, or most any other npm script for this repo?
</details>
yeah, I was looking at the files in the matrix when I made this comment though. 



---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Comment by pcgilday** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Comment by SpainTrain** [comment]
*[.eslintrc.yaml, line 2 \[r3\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNn-NZdAS9SFX_ZAcrf:-KNnKDd7ekLNznxiSZdq:623329510) ([raw file](https://github.com/homezen/redux-variants/blob/707e455336ab9ffc977aba3d3ba0ab3fc29b4d1f/.eslintrc.yaml#L2)):*
<details><summary><i>Previously, pcgilday (Patrick Gilday) wrote…</i></summary>
> weird, I didn't see that comment in my review. 
</details>
dammit, I thought using BTW or FYI resulted in a comment that displayed but did not block review.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Comment by SpainTrain** [comment]
Reviewed 3 of 26 files at r1, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Comment by SpainTrain** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[package.json, line 58 \[r5\]](https://reviewable.io:443/reviews/homezen/redux-variants/1#-KNnNnMuNXd9w0x2JGEL:-KNnNnMuNXd9w0x2JGEM:-1214230482) ([raw file](https://github.com/homezen/redux-variants/blob/c83eadd1b9bcaa3610c4f184b65bb28676a04a83/package.json#L58)):*
> ```JSON
>     "isparta": "^4.0.0",
>     "json-loader": "^0.5.4",
>     "karma": "^0.13.21",
> ```

BTW SMH

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/1)*

**Pull request merged**
