### PR TITLE
:neckbeard: eslint react rules (fixes noref)

### PR DESCRIPTION
**Pull request by SpainTrain**
This change is [Reviewable](https://reviewable.io/reviews/homezen/redux-variants/4)

### CODE REVIEW

**Comment by SpainTrain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/4)*

**Comment by pcgilday** [comment]
CI failing, but after it is fixed - :shipit: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.eslintrc.yaml, line 153 \[r1\]](https://reviewable.io:443/reviews/homezen/redux-variants/4#-KNrtt9rhERQYJNVwLbr:-KNrtt9rhERQYJNVwLbs:1681732968) ([raw file](https://github.com/homezen/redux-variants/blob/a848f1f001684f6b110dad79cc42cbefc7427be1/.eslintrc.yaml#L153)):*
> ```YAML
>         react/no-direct-mutation-state: 2
>         react/no-is-mounted: 2
>         react/no-multi-comp: 0 # proposed
> ```

I _think_ i agree with this. In the 95% case I like it, but there are a couple times (HbudInput) that I think it makes sense to have multiple components in the file.  I think we use the rule then specify the exceptions if they make sense though, it at least forces us to think twice about it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/4#-:-KNrub6omPcuG-icqYiy:536518017)*

**Comment by SpainTrain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[.eslintrc.yaml, line 153 \[r1\]](https://reviewable.io:443/reviews/homezen/redux-variants/4#-KNrtt9rhERQYJNVwLbr:-KNrwNLCs2tmzPW1nT6a:98792210) ([raw file](https://github.com/homezen/redux-variants/blob/a848f1f001684f6b110dad79cc42cbefc7427be1/.eslintrc.yaml#L153)):*
<details><summary><i>Previously, pcgilday (Patrick Gilday) wrote…</i></summary>
> I _think_ i agree with this. In the 95% case I like it, but there are a couple times (HbudInput) that I think it makes sense to have multiple components in the file.  I think we use the rule then specify the exceptions if they make sense though, it at least forces us to think twice about it. 
</details>
I'm going to try to finish the homezen eslint plugin this weekend.  That way proposals can be discussed and impementedl in that repo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/4)*

**Comment by pcgilday** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[.eslintrc.yaml, line 153 \[r1\]](https://reviewable.io:443/reviews/homezen/redux-variants/4#-KNrtt9rhERQYJNVwLbr:-KNrz079X4w_GiKRc-dH:1902464852) ([raw file](https://github.com/homezen/redux-variants/blob/a848f1f001684f6b110dad79cc42cbefc7427be1/.eslintrc.yaml#L153)):*
<details><summary><i>Previously, SpainTrain (Mike S) wrote…</i></summary>
> I'm going to try to finish the homezen eslint plugin this weekend.  That way proposals can be discussed and impementedl in that repo
</details>
:+1: Sweet, I am excited to review that, as I have been curious about eslint plugins and never done one. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/4)*

**Comment by SpainTrain** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/4)*

**Pull request merged**
