### PR TITLE
:money_with_wings: Upgrade to react 16 (fixes mult)

### LINKED ISSUE #205: Ensure compatible with React 15 & 16
When upgrading to React 16, ensure still compatible with latest 15.X

### PR DESCRIPTION
**Pull request by pcgilday**
- Upgrade react deps to react 16
- Compatible with react 15 & 16

closes #205
closes #210

### CODE REVIEW

**Comment by pcgilday** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/homezen/redux-variants/214#-Kwatuq0VZCkdjDLglz8:-Kwatuq0VZCkdjDLglz9:b-1rcru0) (no related file):*
Tests pass using react 15 and 16. I'm having an issue linking locally, so I am unable to test 15 against webapp, but nothing (outside of tests) changed so should be good (although I'll keep working on my local linking issue).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/214)*

**Comment by SpainTrain** [comment]
:shipit:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/homezen/redux-variants/214#-KwbJ3cete5xdHwMwYFc:-KwbJ3cete5xdHwMwYFd:b-80otpq) (no related file):*
BTW 15 isn't really supported if it's not tested going forward

since it is a public repo, documenting explicitly

---

*[package.json, line 73 at r2](https://reviewable.io:443/reviews/homezen/redux-variants/214#-KwbIz4iAnaTNKn3_HXm:-KwbIz4iAnaTNKn3_HXn:b-umrbt7) ([raw file](https://github.com/homezen/redux-variants/blob/bdfe8ab6f43f3c9c12ae559711c480b09828d647/package.json#L73)):*
> ```JSON
>     "react": "~16.0.0",
>     "react-dom": "~16.0.0",
>     "react-test-renderer": "~16.0.0",
> ```

BTW tilde range

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/214#-:-KwbJCA5ss0oqqNKIo2m:b-xr9eiq)*

**Comment by SpainTrain** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/214)*

**Comment by pcgilday** [comment]
Reviewed 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/homezen/redux-variants/214)*

**Pull request merged**
